server:
  servlet:
    context-path: /api/v1  # 모든 API 앞에 /api/v1 prefix 적용

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/runningcity
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 개발: update, 운영: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect