  server:
    servlet:
      context-path: /api/v1  # 모든 API 앞에 /api/v1 prefix 적용
    #compression:            # JSON 응답 gzip 압축. 대역폭 절감, 응답속도 개선.
      #enabled: true
      #mime-types: application/json
      #min-response-size: 1024
  spring:
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

    mvc:              # 비동기 핸들러가 영구 대기하지 않게
      async:
        request-timeout: 15000  # 15s

    jpa:
      hibernate:
        ddl-auto: none  # 개발: update, 운영: validate
      show-sql: true    # 개발 중에만 권장
      properties:
        hibernate:
          format_sql: true
          jdbc.time_zone: UTC

      #database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG16Dialect

    jackson:
      time-zone: UTC
      serialization:
        write-dates-as-timestamps: false

  logging:
    level:
      org.springframework.web: DEBUG